server:
  port: 8080

spring:
  application:
    name: pb-app

  datasource:
    url: jdbc:mysql://localhost:3306/play_buddy?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root

application:
  wechat-applet:
    app-id: 111
    app-secret: 111