server:
  port: 8081

spring:
  application:
    name: pb-admin

  datasource:
    url: jdbc:mysql://localhost:3306/play_buddy?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root